### ISSUE TITLE
How to use with domoticz docker image

### ISSUE THREAD

**Issue by kipusoep** [majki09/domoticz_lg_thinq_plugin#5]
Hi!

The apt packages are not all available inside the official domoticz docker image.
Following the installation steps will work for the running container, but whenever it gets recreated, it'll be all gone.
So how could I use this with the docker image? I'm afraid that I'll have to create my own image based on the official image, or are there other ways?

**Comment by majki09** [comment]
Hi @kipusoep.
I have played with domoticz and docker recently and found that both plugin and `wideq_state.json` file have to be under */userdata* folder. Since that folder is a docker volume this will keep them safe while container re-creations. Also I've made changes (392f5c1550d68c7887fa2d94bf5df958592714f9) to the code to have state file in the plugin folder - no more moving after generation! 😄

**Comment by kipusoep** [comment]
Works now :-)
